name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v2 # Use the latest version of the checkout action
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x' # Use Node.js 16
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/@treelunar/feed"
